#ifndef __EVENTTYPES__
#define __EVENTTYPES__

#define EVENT_OFFSET 0x0000
#define CUSTOM_EVENT_START 0x5000

enum EventTypes: int
{
	EVENT_INIT = EVENT_OFFSET + 1,
	EVENT_DESTROY = EVENT_OFFSET + 2,
	EVENT_START = EVENT_OFFSET + 3,
	EVENT_PAUSE = EVENT_OFFSET + 4,
	EVENT_KEY = EVENT_OFFSET + 0x0010,
	EVENT_KEYDOWN = EVENT_KEY + 1,
	EVENT_KEYUP = EVENT_KEY + (1 << 1),
	EVENT_MOUSE = EVENT_OFFSET + 0x0020,
	EVENT_MOUSEDOWN = EVENT_MOUSE + 1,
	EVENT_MOUSEUP = EVENT_MOUSE + (1 << 1),
	EVENT_MOUSEMOVE = EVENT_MOUSE + (1 << 2)
};

#endif